# Generated by Django 3.2.13 on 2023-01-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_mc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay_question',
            name='verif_function',
            field=models.CharField(blank=True, help_text='Enter the name of the functionthat will correct the question', max_length=100, verbose_name='Function name'),
        ),
    ]
