openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/experiments:
    get:
      operationId: listExperiments
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Experiment'
          description: ''
      tags:
      - api
components:
  schemas:
    Experiment:
      type: object
      properties:
        name:
          type: string
          maxLength: 64
        description:
          type: string
        config:
          type: object
        scientific_area:
          type: string
          maxLength: 64
        lab_type:
          type: string
          maxLength: 32
      required:
      - name
      - description
      - scientific_area
      - lab_type
