# Generated by Django 3.2.13 on 2023-03-05 18:20

from django.db import migrations, models
import mc_quiz.quiz_mc.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_mc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='decimal_precision',
            field=models.IntegerField(default=mc_quiz.quiz_mc.models.Sitting.randomize_decimal_precision, verbose_name='Decimal Precision'),
        ),
    ]
