# Generated by Django 3.2.13 on 2023-03-05 22:15

from django.db import migrations, models
import mc_quiz.quiz_mc.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_mc', '0003_question_rounding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', 'content'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.PositiveIntegerField(blank=True, help_text='Question priority to show in quiz, smaller means bigger priority', null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='decimal_precision',
            field=models.PositiveIntegerField(default=mc_quiz.quiz_mc.models.Sitting.randomize_decimal_precision, verbose_name='Decimal Precision'),
        ),
    ]
