# Generated by Django 3.2.13 on 2023-04-12 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0036_alter_result_result_type'),
        ('quiz_mc', '0004_auto_20230305_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', django.db.models.expressions.OrderBy(django.db.models.expressions.F('priority'), nulls_last=True)], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='category',
            name='apparatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='free.apparatustype', verbose_name='Apparatus Type'),
        ),
    ]
