# Generated by Django 3.2.13 on 2023-04-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_mc', '0005_auto_20230412_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='apparatus',
            new_name='apparatus_type',
        ),
    ]
