# Generated by Django 3.2.13 on 2023-04-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0036_alter_result_result_type'),
        ('quiz_mc', '0006_rename_apparatus_category_apparatus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='apparatus_type',
        ),
        migrations.AddField(
            model_name='category',
            name='apparatus_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='free.protocol', verbose_name='Apparatus Protocol'),
        ),
    ]
