# Generated by Django 3.2.13 on 2023-04-15 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free', '0036_alter_result_result_type'),
        ('quiz_mc', '0007_auto_20230412_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='apparatus_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_mc_category_apparatus_protocol', to='free.protocol', verbose_name='Apparatus Protocol'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mc_progress_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mc_question_category', to='quiz_mc.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mc_question_subcategory', to='quiz_mc.subcategory', verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mc_quiz_category', to='quiz_mc.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_mc_sitting_execution', to='free.execution', verbose_name='Execution'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mc_sitting_quiz', to='quiz_mc.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mc_sitting_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_mc_subcategory_category', to='quiz_mc.category', verbose_name='Category'),
        ),
    ]
