# Generated by Django 3.2.13 on 2023-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0033_alter_result_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('f', 'Final'), ('p', 'Partial')], max_length=1, verbose_name='Result type'),
        ),
    ]
